### ISSUE TITLE
Missing client_location (beta4)

### ISSUE THREAD

**Issue by jalberto** [elastic/packetbeat#359]
- packetbeat b4 (logstash ssl as output)
- logstash 2.0
- elk 2.0

I downloaded GeoLiteCiry,dat, there is not errors in foreground (verbose) but the field is missing.

Config:
```
shipper:
  name:
  tags: ["foo"]
  ignore_outgoing: true
  geoip:
    paths: ["/etc/packetbeat/GeoLiteCity.dat", "/usr/share/GeoIP/GeoIP.dat"]
interfaces:
  device: any
  type: af_packet
  buffer_size_mb: 50
 http:
    ports: [80, 8080, 8000, 443]
    hide_keywords: ['pass', 'password', 'passwd']
    send_request:  true
    send_response: true
```

Thanks!
