### ISSUE TITLE
PCAP waitstop / publisher rc1 regression  ?

### ISSUE THREAD

**Issue by McStork** [elastic/packetbeat#365]
Hello,
PCAP parsing with Packetbeat rc1 behave differently than beta4. I ran the below config file with the beta4, then with rc1 version. With beta4, Packetbeat keeps publishing when the waitstop is set. However, with rc1, it doesn't publish to Logstash when Packetbeat is waiting (traffic stops in tcpdump).

Example of failing command:
```
packetbeat -c /etc/packetbeat/packetbeat_logstash.yml -e -v -t -waitstop 30 -I largefile.pcap
```
PCAP file is 150Mb.
The program is run without debug mode to make it faster.

Logstash is v2.0.0.

Packetbeat config file:
```
interfaces:
        type: pcap

protocols:
        dns:
                ports: [53]
                transaction_timeout: 1

output:
        logstash:
                enabled: true
                hosts: ["127.0.0.1:5044"]
```

Logstash config:
```
input {
  beats {
    port => 5044
  }
}
filter {
    metrics {
        meter => "documents"
        add_tag => "metric"
        flush_interval => 60
    }
}
output {
   if "metric" in [tags] {
       stdout {
           codec => line {
               format => "1m rate: %{[documents][rate_1m]} ( %{[documents][count]} )"
           }
       }
   }
   null{}
}
```
